### PR TITLE
 appveyor CI + x64

### PR DESCRIPTION
**Pull request by chcg**
- appveyor.yml CI config, see https://www.appveyor.com/docs/deployment/github/#provider-settings for automatic deployment to github releases
- corrected vcxprocj to build for all configs
- updated n++ input files with current versions from https://github.com/npp-plugins/plugintemplate

, see https://ci.appveyor.com/project/chcg/pynpp/build/1.2.1.3

### CODE REVIEW

**Comment by mpcabd** [comment]
Thank you for this very helpful commit @chcg 😃

**Comment by chcg** [comment]
Your welcome. To create a new release a new tag should be sufficient now as you added the token. Appveyor will deploy zip packages to the releases as these are required from the PluginManager.

As toolchain v140_xp is used so the dll is still compatible with windows xp sp3 systems or newer. Just v140 would require vista or newer, see e.g. https://stackoverflow.com/questions/36226812/difference-between-toolset-v140-and-v140-xp-v110-and-v110-xp-and-so-on.

**Comment by chcg** [comment]
@mpcabd Are you planning to release a x64? Release 1.2.1 could not be used by the pluginManager as it is not available as zip. Could you please provide a zip release 1.2.1.

**Comment by CollinChaffin** [comment]
@mpcabd Can you please reply or let us know if this is abandoned?

**Pull request merged**
